uuid = "74807b76-c451-419f-bbd4-42a78e2444a6"
name = "ReplayGain 2.0"
authors = ["complexlogic", "Philipp Wolfer"]
maintainers = ["MusicBrainz Picard Team"]
description = "Calculates ReplayGain information for tracks and albums"
api = ['3.0']
license = "GPL-2.0"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
categories = ["metadata", "ui"]

long_description = """
Calculates ReplayGain information for tracks and albums according to the
[ReplayGain 2.0 specification](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification).
This plugin depends on the ReplayGain utility [rsgain](https://github.com/complexlogic/rsgain). Users
are required to install rsgain and set its path in the plugin settings before use.

#### Usage
Select one or more tracks, albums, or clusters then right click and select Plugin->Calculate ReplayGain.
The plugin will calculate ReplayGain information for the selected items and display the results in the
metadata window. Click the save button to write the tags to file.

The following file formats are supported:

- MP3 (.mp3)
- FLAC (.flac)
- Ogg (.ogg, .oga, spx)
- Opus (.opus)
- MPEG-4 Audio (.m4a, .mp4)
- Wavpack (.wv)
- Monkey's Audio (.ape)
- WMA (.wma)
- MP2 (.mp2)
- WAV (.wav)
- AIFF (.aiff)
- TAK (.tak)
- MusePack *(Stream Version 8 only)* (.mpc)

This plugin is based on the original ReplayGain plugin by Philipp Wolfer and Sophist.
"""
homepage = "https://github.com/metabrainz/picard-plugin-replaygain2"
report_bugs_to = "https://tickets.metabrainz.org/issues/?filter=13410"

[description_i18n]
de = "Berechnet ReplayGain-Informationen für Titel und Alben"
nl = "Berekent ReplayGain-informatie over nummers en uitgaven"

[long_description_i18n]
de = """
Berechnet ReplayGain-Informationen für Titel und Alben gemäß der
[ReplayGain-2.0-Spezifikation](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification).
Dieses Plugin hängt vom ReplayGain-Tool [rsgain](https://github.com/complexlogic/rsgain) ab. Benutzer
müssen rsgain installieren und den Pfad dazu in den Plugin-Einstellungen festlegen, bevor sie es verwenden können.

#### Verwendung
Wählen Sie einen oder mehrere Titel, Alben oder Cluster aus, klicken Sie dann mit der rechten Maustaste und wählen Sie Plugin -> ReplayGain berechnen.
Das Plugin berechnet die ReplayGain-Informationen für die ausgewählten Elemente und zeigt die Ergebnisse
im Metadatenfenster an. Klicken Sie auf „Speichern“, um die Tags in die Datei zu schreiben.

Die folgenden Dateiformate werden unterstützt:

- MP3 (.mp3)
- FLAC (.flac)
- Ogg (.ogg, .oga, .spx)
- Opus (.opus)
- MPEG-4 Audio (.m4a, .mp4)
- WavPack (.wv)
- Monkey’s Audio (.ape)
- WMA (.wma)
- MP2 (.mp2)
- WAV (.wav)
- AIFF (.aiff)
- TAK (.tak)
- Musepack *(nur Stream-Version 8)* (.mpc)

Dieses Plugin basiert auf dem ursprünglichen ReplayGain-Plugin von Philipp Wolfer und Sophist.
"""
